name: RankUp
main: rankup\RankUp
version: 0.3.1
author: Falkirks
api: [1.4.0, 3.0.0-ALPHA5]
load: POSTWORLD
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney", "PurePerms"]
permissions:
 rankup:
  default: true
  children:
    rankup.rankup:
      default: true
      description: Allow ranking up
    rankup.admin:
      default: op
      description: Manage RankUp and view statistics
    rankup.groups:
      default: false
      description: Do NOT set this. It is used for group managment.
